AllCops:
  TargetRubyVersion: 2.6

Rails/ContentTag:
  Enabled: false

# With the caveat that devs go to Preferences > Editor > General > On Save, and apply the rule of
# Remove trailing spaces on all lines.
Layout/TrailingWhitespace:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

NumericPredicate:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets
